### ISSUE TITLE
New GeoDjangoMixin configuration

### ISSUE THREAD

**Issue by banesullivan** [girder/django-composed-configuration#141]
This configuration is used across all projects that install the RGD apps and any projects hoping to use geodjango.

https://github.com/ResonantGeoData/RD-OpenGeo/blob/98aff6fe06348ba1556d017e2ded5e3dd17c1265/opengeo/settings.py#L16-L36

Should we migrate this upstream to composed-configurations so that new projects can more easily utilize this and so that we only have to maintain it in one spot?

Other places it appears:

- https://github.com/ResonantGeoData/RD-WATCH/blob/488986417449bfde0b2cab40c8578b57c7db5fed/watch/settings.py#L18-L38
- https://github.com/ResonantGeoData/RD-OASIS/blob/8dd3c922a8b57123b6a1f4fbc85d92afc24f5109/rdoasis/settings.py#L18-L38

**Comment by brianhelba** [comment]
I don't think this is in scope for Composed-Configuration, as it would certainly be an optional mixin, and I think it's too ambitious to support mix-and-match downstream composition of mixins officially (of course, it's expected and acceptable that downstreams will choose to do this in an unsupported way).

Any downstream package like RGD should be able to depend on Composed-Configuration and publish their own mixin classes though. If something is blocking that, please file a bug, so it can be addressed directly.

Otherwise, I think these particular settings are too particular to RGD to be useful upstream. I'm closing this accordingly, but feel free to comment if you have other thoughts.
